# version: '3.8'

# services:

#   db:
#     image: postgres:14
#     restart: always
#     container_name: postgresql
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     environment:
#       - DATABASE_HOST=127.0.0.1
#       - POSTGRES_USER=adminAuto
#       - POSTGRES_PASSWORD=12345678
#       - POSTGRES_DB=automanager

#   admin_db:
#     image: dpage/pgadmin4:8.4
#     container_name: pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: automanager123@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: 12345678
#     ports:
#       - "80:80"
#     depends_on:
#       - db

#   backend:
#     build: 
#       context: ./backend
#       dockerfile: dockerfile
#     container_name: django
#     command: >
#       sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     environment:
#       - POSTGRES_NAME=automanager
#       - POSTGRES_USER=adminAuto
#       - POSTGRES_PASSWORD=12345678
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ./client
#       dockerfile: dockerfile
#     container_name: react
#     restart: always
#     depends_on:
#        - backend
#     ports:
#       - "8085:80"

version: '3.8'

services:

  db:
    image: postgres:14
    restart: always
    container_name: postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  admin_db:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: automanager123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "80:80"
    depends_on:
      - db

  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    container_name: django
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: react
    restart: always
    depends_on:
       - backend
    ports:
      - "8085:80"
    